<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:macro name="laser" params="name parent xyz rpy meshes use_gpu:=false" >

  <xacro:property name="base_width" value="0.05" /> <!-- (m) base width of housing -->
  <xacro:property name="base_depth" value="0.05" /> <!-- (m) base depth of housing -->
  <xacro:property name="base_height" value="0.07" /> <!-- (m) base heigth of housing -->
  <xacro:property name="laser_height" value="${base_height / 2 + 0.02275}" /> <!-- (m) origin of the laser measurement -->

  <xacro:if value="${use_gpu}">
    <xacro:property name="sensor_type" value="gpu_ray" />
    <xacro:property name="plugin_name" value="libgazebo_ros_gpu_laser.so" />
  </xacro:if>
  <xacro:unless value="${use_gpu}">
    <xacro:property name="sensor_type" value="ray" />
    <xacro:property name="plugin_name" value="libgazebo_ros_laser.so" />
  </xacro:unless>
  

  <joint name="${parent}_${name}_base_joint" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="${xyz}" rpy="${rpy}"/>
    <parent link="${parent}"/>
    <child link="${name}_base"/>
  </joint>

  <joint name="${parent}_${name}_joint" type="fixed">
    <axis xyz="0 0 1" />
    <origin xyz="0 0 ${laser_height}" rpy="0 0 0"/>
    <parent link="${name}_base"/>
    <child link="${name}"/>
  </joint>

  <link name="${name}_base">
    <collision>
      <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_width} ${base_depth} ${base_height}"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="${meshes}/hokuyo.dae"/>
      </geometry>
    </visual>
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <link name="${name}">
  </link>

    <gazebo reference="${name}">
        <sensor name="laser" type="${sensor_type}">
        <pose>0 0 0 0 0 0</pose>
          <ray>
            <scan>
              <horizontal>
                <!-- The URG-04LX-UG01  has  683 steps with 0.35139 Degree resolution -->
                <resolution>1</resolution>
                <max_angle>2.0944</max_angle> <!-- 120 Degree -->
                <min_angle>-2.0944</min_angle> <!-- -120 Degree -->
                <samples>683</samples>
              </horizontal>
            </scan>
            <range>
              <min>0.08</min>
              <max>5</max>
              <resolution>0.01</resolution>
            </range>
          </ray>

          <plugin name="laser" filename="${plugin_name}" >
            <robotNamespace></robotNamespace>
            <topicName>${name}/scan</topicName>
            <frameName>${name}</frameName>
          </plugin>
          <!--
          <plugin name="laser" filename="libRayPlugin.so" />
          -->

          <always_on>1</always_on>
          <update_rate>10</update_rate>
          <visualize>true</visualize>
        </sensor>
    </gazebo>
</xacro:macro>

</robot>
