<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="amiro" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="0.4" /> <!-- amiro base mass -->
  <xacro:property name="radius" value="0.05" /> <!-- amiro base radius -->
  <xacro:property name="height" value="0.08" /> <!-- amiro base height -->
  <xacro:property name="wheel_radius" value="0.03" /> <!-- amiro wheel radius -->
  <xacro:property name="wheel_height" value="0.01" /> <!-- amiro wheel height -->
  <xacro:property name="wheel_sep" value="0.069" /> <!-- amiro wheel seperation -->
  <xacro:property name="wheel_dia" value="0.05571" /> <!-- amiro wheel diameter -->
  <xacro:property name="wheel_mass" value="0.02" /> <!-- amiro wheel diameter -->
  <xacro:property name="base_link_clearance" value="0.0026" /> <!-- space between floor and amiro base -->
  <xacro:property name="base_link_height" value="${base_link_clearance + height / 2}" /> <!-- amiro base link height -->

  <xacro:property name="prefix" value="" /> <!--""-->
  <xacro:property name="base_link" value="${prefix}base_link" /> <!-- amiro base link -->
  <xacro:property name="left_wheel_link" value="${prefix}left_wheel_link" /> <!-- amiro wheel link -->
  <xacro:property name="right_wheel_link" value="${prefix}right_wheel_link" /> <!-- amiro wheel link -->
  <xacro:property name="right_wheel_joint" value="${prefix}right_wheel_joint" /> <!-- amiro wheel joint -->
  <xacro:property name="left_wheel_joint" value="${prefix}left_wheel_joint" /> <!-- amiro wheel joint -->
  <xacro:property name="odom" value="${prefix}odom" /> <!-- amiro odometry topic/tf -->
  <xacro:property name="cmd_vel" value="${prefix}cmd_vel" /> <!-- amiro differential command  topic -->

  <xacro:property name="update_rate" value="$(arg update_rate)" /> <!-- update rate for the plugins and TFs -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find amiro_description)/urdf/amiro.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find amiro_description)/urdf/materials.xacro" />

  <!-- Base Link -->
  <link name="${base_link}">
    <!-- Base -->
    <collision name='base_collision'>
      <origin xyz="0 0 ${base_link_height}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${height}" radius="${radius}"/>
      </geometry>
    </collision>

    <visual name='base_visual'>
      <origin xyz="0 0 ${base_link_height}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${height}" radius="${radius}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial name='base_inertia'>
      <origin xyz="0 0 ${base_link_height}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
        ixx="0.0012" ixy="0.0" ixz="0.0"
        iyy="0.0012" iyz="0.0"
        izz="0.005"/>
    </inertial>

    <!-- Front caster -->
    <collision name='caster_front_collision'>
      <origin xyz="0.042 0 0.001" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.002"/>
      </geometry>
    </collision>

    <visual name='caster_front_visual'>
      <origin xyz="0.042 0 0.001" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.002"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial name='caster_front_inertia'>
      <origin xyz="0.042 0 0.001" rpy="0 0 0"/>
      <mass value="0.01"/>
    </inertial>
    
    <!-- Back caster -->
    <collision name='caster_back_collision'>
      <origin xyz="-0.042 0 0.001" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.002"/>
      </geometry>
    </collision>

    <visual name='caster_back_visual'>
      <origin xyz="-0.042 0 0.001" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.002"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial name='caster_back_inertia'>
      <origin xyz="-0.042 0 0.001" rpy="0 0 0"/>
      <mass value="0.01"/>
    </inertial>
  </link>

  <!-- Left wheel -->
  <joint name="${left_wheel_joint}" type="continuous">
    <parent link="${base_link}"/>
    <child link="${left_wheel_link}"/>
    <origin xyz="0 ${wheel_radius} 0.02" rpy="0 ${PI/2} ${PI/2}"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.1"/>
  </joint>

  <link name="${left_wheel_link}">
    <collision>
      <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <visual>
      <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <cylinder length="0.01" radius="0.03"/>
      <mass value="${wheel_mass}"/>
      <inertia
        ixx="0.0000068453" ixy="0.0" ixz="0.0"
        iyy="0.0000068453" iyz="0.0"
        izz="0.0000075625"/>
    </inertial>
  </link>

  <!-- Right wheel -->
  <joint name="${right_wheel_joint}" type="continuous">
    <parent link="${base_link}"/>
    <child link="${right_wheel_link}"/>
    <origin xyz="0 -${wheel_radius} 0.02" rpy="0 ${PI/2} ${PI/2}"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.1"/>
  </joint>

  <link name="${right_wheel_link}">
    <collision>
      <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <visual>
      <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
      <geometry>
        <cylinder length="${wheel_height}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <cylinder length="0.01" radius="0.03"/>
      <mass value="${wheel_mass}"/>
      <inertia
        ixx="0.0000068453" ixy="0.0" ixz="0.0"
        iyy="0.0000068453" iyz="0.0"
        izz="0.0000075625"/>
    </inertial>
  </link>

</robot>
